from pymilvus import CollectionSchema, DataType, FieldSchema


fields: list[FieldSchema] = [
    FieldSchema(name="id", dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name="id_card_number", dtype=DataType.VARCHAR, max_length=20),
    
    FieldSchema(name="hospitalize_num", dtype=DataType.VARCHAR, max_length=50),
    FieldSchema(name="name", dtype=DataType.VARCHAR, max_length=50),
    FieldSchema(name="case_number", dtype=DataType.VARCHAR, max_length=50),
    FieldSchema(name="sex", dtype=DataType.VARCHAR, max_length=50),
    FieldSchema(name="age", dtype=DataType.VARCHAR, max_length=50),
    FieldSchema(name="phone_number", dtype=DataType.VARCHAR, max_length=50),
    FieldSchema(name="seizure_evolution", dtype=DataType.VARCHAR, max_length=600),
    FieldSchema(name="seizure_duration", dtype=DataType.VARCHAR, max_length=20),
    FieldSchema(name="seizure_freq", dtype=DataType.VARCHAR, max_length=20),
    FieldSchema(name="maternal_pregnancy_age", dtype=DataType.VARCHAR, max_length=20),
    FieldSchema(name="pregnancy_num", dtype=DataType.VARCHAR, max_length=10),
    FieldSchema(name="birth_weight", dtype=DataType.VARCHAR, max_length=20),
    FieldSchema(name="head_c", dtype=DataType.VARCHAR, max_length=15),
    FieldSchema(name="blood_urine_screening", dtype=DataType.VARCHAR, max_length=30),
    FieldSchema(name="copper_cyanin", dtype=DataType.VARCHAR, max_length=25),
    FieldSchema(name="csf", dtype=DataType.VARCHAR, max_length=25),
    FieldSchema(name="genetic_test", dtype=DataType.VARCHAR, max_length=25),
    FieldSchema(name="head_ct", dtype=DataType.VARCHAR, max_length=25),
    FieldSchema(name="head_mri", dtype=DataType.VARCHAR, max_length=25),
    FieldSchema(name="scalp_eeg", dtype=DataType.VARCHAR, max_length=25),
    FieldSchema(name="precipitating_factor", dtype=DataType.VARCHAR, max_length=300),
    FieldSchema(name="childhood_onset", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="aed", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="epilepsy_surgery", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="simple_sensory_seizure", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="is_parent_febrile_convulsion", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="pregnancy_diseases", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="infancy_onset", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="motor_seizure", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="metabolic_disorders", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="postictal_manifestation", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="symptomatic_epilepsy", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="have_surgery_history", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="automatism", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="generalized_motor_seizures", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="pigmentation", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="local_motor_seizures", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="autonomic_nerves", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="cognition", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="other_epilepsy_syndrome", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="electrolyte", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="neonatal_onset", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="vaccination_history", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="is_relatives_have_epilepsy", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="lactate", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="growth_milestone", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="growth_retardation", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="adolescent_adult_onset", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="stunting", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="blood_ammonia", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="generalized_non_motor_seizures", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="learning_difficulties", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="focal_non_motor_seizures", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="overprotected", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="has_febrile_seizures_history", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="has_neonatal_convulsion", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="adhd", dtype=DataType.VARCHAR, max_length=200),
    FieldSchema(name="has_severe_jaundice", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="feeding_difficulties", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="emotion_or_feeling", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="epilepsy_syndromes_no_specifically_related_to_age", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="ketogenic_diet", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="stained_amniotic_fluid", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="blood_transfusion_history", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="trauma_history", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="focal_secondary_bilateral_tonic_clonic_seizures", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="is_parents_consanguineous_married", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="fall", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="has_birth_asphyxia", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="convulsion_history", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="growth_regression", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="high_psychological_pressure", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="vomit", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="accompanying_fever", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="delivery_mode", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="diarrhea", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="tic", dtype=DataType.VARCHAR, max_length=200),
    # FieldSchema(name="autism", dtype=DataType.VARCHAR, max_length=200),
]

schema = CollectionSchema(fields=fields, description='')
